### ISSUE TITLE
Fix Seed Generation Scripts

### ISSUE THREAD

**Issue by erikaheidi** [erikaheidi/hacktober-board#1]
The Laravel Seed generation scripts must be updated to reflect the current data being stored. 

Reference: [Laravel Docs](https://laravel.com/docs/5.8/seeding)

**Comment by sadaimudiNaadhar** [comment]
@erikaheidi  Hello can I pick this?

**Comment by erikaheidi** [comment]
Hey @sadaimudiNaadhar , I'm sorry but someone sent a PR for this issue before you replied, and the PR was merged.
