### ISSUE TITLE
Add "how to set up a dev environment using DDEV" - section to readme

### ISSUE THREAD

**Issue by pulponair** [erikaheidi/hacktober-board#10]
There is a lot of php developers using ddev as a dev stack. 
Including instructions will help addressing a wider audience.

- [x]  .ddev Configuration
- [x]  Add .env.ddev 
- [x] Update README.md

**Comment by pulponair** [comment]
@erikaheidi Do you think it is usefull? I could do that since i v it up and running anyway (except for the README of course).

**Comment by erikaheidi** [comment]
I see I should had replied to this earlier, but I didn't. I would prefer to stick with the basic setup for now, I am not familiar with this vendor and I prefer to keep things simple whenever possible, I don't really see a need at the moment for this project.

**Comment by pulponair** [comment]
>I am not familiar with this vendor and I prefer to keep things simple whenever possible, I don't really see a need at the moment for this project.

Ok :)
Personal note: You should get yourself familar with DDEV. It is damn cool and makes project boarding a peace of cake :).
