### ISSUE TITLE
Apply naming conventions to views and partials

### ISSUE THREAD

**Issue by pulponair** [erikaheidi/hacktober-board#37]
Views should be relocated to:

/<ControllerName>/<ActionName>.blade.php
e.g.
/project/list.blade.php

Don't set the view manually guess it from the controller and actionname within baseView -> protected function resolveView()

**Comment by pulponair** [comment]
@erikaheidi if you are working on that anyway: would you mind?:)

**Comment by erikaheidi** [comment]
Sure that makes sense! I will include this change
