### ISSUE TITLE
Create endpoint to list all projects

### ISSUE THREAD

**Issue by erikaheidi** [erikaheidi/hacktober-board#7]
Sometimes, what a user is looking for is a good project to get involved with, rather than just looking for random issues that they can contribute to. It would be good to be able to list all projects.

- Endpoint: `/projects`
- Projects should be ordered by the number of stars they have
- Pagination is needed
- Don't worry about adding a link to this new endpoint, this will be handled in a separate issue.

**Comment by pulponair** [comment]
i'll grab this one

**Comment by erikaheidi** [comment]
:+1:
