### ISSUE TITLE
Create a menu in the footer area

### ISSUE THREAD

**Issue by erikaheidi** [erikaheidi/hacktober-board#8]
Add a column to the footer area for linking to the new routes created in #2 and #7 . Mostly front-end work :art:

**Comment by hallowcard13** [comment]
I'll grab this one

**Comment by erikaheidi** [comment]
:+1:

**Comment by hallowcard13** [comment]
Hi @erikaheidi  what should be the link name for the two routes ?

**Comment by erikaheidi** [comment]
PR merged and deployed :100:
