### ISSUE TITLE
Create an endpoint to paginate through all issues

### ISSUE THREAD

**Issue by erikaheidi** [erikaheidi/hacktober-board#9]
Currently, the index page shows 4 items in the "Newest Issues" section, and there is no way to navigate through the newest issues in order to get more. It would be useful to have an endpoint where you can navigate through the issues in a chronological way.

You can use the current issue listing per language as a base for the new view.

**Comment by lacasera** [comment]
will work on this

**Comment by lacasera** [comment]
![Screen Shot 2019-10-09 at 12 04 45 PM](https://user-images.githubusercontent.com/8544587/66479959-154a7400-ea8d-11e9-8bec-733fb954079c.png)

**Comment by lacasera** [comment]
notice the next and previous links to paginate through newest issues. if this is ok with you, will open the pr. if not, let me know what needs to be done

**Comment by erikaheidi** [comment]
Hey @lacasera ! I think I might have not clarified enough in the description, but what I meant was a separate page / route, for instance: `/issues` to show the issues using pagination, it should be similar to the issues listing per language and per label but there should be no filters, so we can show all the issues. 

In the main page, I think we can add just a link to this page, no need to paginate in the index itself. 

Please let me know if you have any questions! Thank you for working on this issue!

**Comment by pulponair** [comment]
@lacasera Tell me if you want me to overtake i v done that for Projects already and adapting it for issues is a peace of cake 
//cc @erikaheidi

**Comment by lacasera** [comment]
Sure @pulponair . I've been pretty swamped with work.
